### ISSUE TITLE
Preview goes to PDF instead of HTML

### ISSUE THREAD

**Issue by eeintech** [donhauser/wagtail-pdf#2]
I have my `ROUTE_CONFIG` set to use HTML first:
``` python
ROUTE_CONFIG = [
        ("pdf", r'^pdf/$'),
        ("html", r'^$'),
    ]
```
But Wagtail's preview always goes to the PDF view.

**Comment by donhauser** [comment]
The order is important, you need to set "html" in the first place if you want to display the html page by default using wagtails preview.

```py
ROUTE_CONFIG = [
        ("html", r'^$'),
        ("pdf", r'^pdf/$'),
    ]
```

Thank you for the question though, I will change this in the readme

**Comment by eeintech** [comment]
Wonderful, it works fine with the right order :+1:
