### ISSUE TITLE
Support for tables?

### ISSUE THREAD

**Issue by eeintech** [donhauser/wagtail-pdf#3]
Hey there,

I'm now trying to render a `TableBlock` (https://docs.wagtail.io/en/stable/reference/contrib/table_block.html) with LaTex but I only get the HTML in the rendered PDF:
```
¡table¿
¡caption¿Connectors¡/caption¿
¡thead¿ ¡tr¿
¡th scope=”col” ¿
Port
¡/th¿
¡th scope=”col” ¿
Description
¡/th¿
¡/tr¿ ¡/thead¿
¡tbody¿
¡tr¿
¡td ¿
USB-C
¡/td¿
¡td ¿
Full-Speed
¡/td¿
¡/tr¿
¡tr¿
¡td ¿
Virtual Port
¡/td¿
¡td ¿
Serial Link
¡/td¿
¡/tr¿
¡/tbody¿ ¡/table¿
```

Am I missing some magic to make this work? :smile:

**Comment by eeintech** [comment]
Oops forgot to mention I switched the interpreter to make the table of contents work. In my settings:
``` python
LATEX_INTERPRETER='latexmk -pdf'
```

Recommended in https://github.com/weinbusch/django-tex/pull/4

EDIT: `pdflatex` also seem to have the same problem so could be upstream

**Comment by donhauser** [comment]
Hi,
when you are using the LaTeX mode, the blocks/fields are still constructed in HTML format first.
This means that every HTML tag (e.g. `<i></i>`) needs to be mapped to its corresponding LaTeX command (e.g. `textit{}` ).

Currently (as of version 0.1.2) only the following tags are supported:
`<i>`, `<b>`, `<p>`, `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<ul>`, `<ol>`, `<li>`, `<br>`, `<a>`, `<img>`

The mapping is done rather simple with `SimpleHtmlToLatexParser`. I've only implemented a few tags to make at least RichTextFields supported.

If you want to hook in a customized parser (e.g. for tables), you can override `HTML_TO_LATEX_PARSER` in your settings with a class that implements:
```py
    def parse(self, html):
        # TODO your custom latex parsing here
        latex =

        return mark_safe(latex)
```

Also you could inherit from `SimpleHtmlToLatexParser` and extend the `mapping` dictionary with the latex synonyms for tables.

If you find a nice solution for this, you are very welcome to create a pull request!

**Comment by eeintech** [comment]
@donhauser What do you think of #4 ?

**Comment by donhauser** [comment]
@eeintech Looks good, I will merge your commit into this project later, thank you very much!

**Comment by donhauser** [comment]
@eeintech Thank you for your commit!
Wagtail (contrib) Tables --> LaTeX Tables is now supported in version 0.1.3

**Comment by eeintech** [comment]
Thanks!
