### ISSUE TITLE
Error when creating instance that inherits PdfViewPageMixin

### ISSUE THREAD

**Issue by pmontepagano** [donhauser/wagtail-pdf#5]
When creating an instance of a simple model like this:

```python
class ExamplePage(PdfViewPageMixin, Page):
  pass
```

I get an exception: `AttributeError: 'NoneType' object has no attribute 'endswith'`

I think we should check if the `Page` instance has it's `url` attribute set in `MultipleViewPageMixin`'s `__init__` method:

**Comment by donhauser** [comment]
Thank you for your contribution!
