### ISSUE TITLE
Generate pdf file from a Page as Wagtail Document 

### ISSUE THREAD

**Issue by ramibch** [donhauser/wagtail-pdf#9]
Hi Jonas, you have a great package, love it! 

Do you think is it possible to create easily a function that return pdf file object as a Wagtail Document? Where should I start if I want to implement that? I tried to check your code to do that but I am not that pro. I need to advices. 

Many thanks!

**Comment by donhauser** [comment]
Thank you very much, it's nice that the package suits your needs :+1: 

From my experience directly hooking into Wagtails Documents will not be too easy, as the documents are directly fetched from the database and extending other package's db-models can be pretty tough.

In my opinion the easiest way therefore would be to leave the Wagtails Document code as it is and create a document which simply points to store a rendered version of the .pdf file on the server instead *(Lets assume you are rendering some class `PdfModel`)*:
- add document reference attribute to you `PdfModel` , e.g. `PdfModel.linkedDocument`
- if a new Instance of `PdfModel` is created you trigger the creation of a new wagtail document and store it into `linkedDocument`
- if the `PdfModel` instance is deleted, you also remove the linked document
- You'll need to render and to store the rendered .pdf file after the creation and updating of a `PdfModel`
  - This is going to be a little tricky, one possibility is to simply access the pdfs-views URL on your server
  - The nicer way would be to call the render function [(django-weasyprint implementation)](https://github.com/fdemmer/django-weasyprint/blob/main/django_weasyprint/views.py) and to store the pdf somewhere

Hope this helps to get you started, I think this should actually be quite doable :)
